students=int(input('enter number of students:'))
apples=int(input('enter number of apples:'))
d=(apples//students)
r=(apples%students)
print(f"each students {d}")
print(f"the remaining apples are {r}")
